version: "3.7"

services:
  web:
    image: josephgotran/web-service:latest
    container_name: web_service
    ports:
      - "5731:80"
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.web.loadbalancer.server.port=80"
      - "traefik.http.routers.web.rule=Host(`joseph.works`)"
      - "traefik.http.routers.web.entrypoints=websecure"
      - "traefik.http.routers.web.tls.certresolver=letsencrypt"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - traffic_net

  # Development service (optional - for hot reload)
  dev:
    image: node:20-alpine
    working_dir: /app
    command: npm run dev
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:8000
    profiles:
      - dev
    networks:
      - traffic_net

networks:
    traffic_net:
        external: true
