"""init

Revision ID: ed0d32d4e9a5
Revises: 
Create Date: 2025-10-16 14:51:01.149248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ed0d32d4e9a5"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "routes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("route_id", sa.String(length=255), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("origin_lat", sa.Float(), nullable=False),
        sa.Column("origin_lng", sa.Float(), nullable=False),
        sa.Column("destination_lat", sa.Float(), nullable=False),
        sa.Column("destination_lng", sa.Float(), nullable=False),
        sa.Column("total_distance", sa.Integer(), nullable=False),
        sa.Column("total_duration", sa.Integer(), nullable=False),
        sa.Column("polyline", sa.Text(), nullable=True),
        sa.Column("route_type", sa.String(length=50), nullable=True),
        sa.Column("vehicle_type", sa.String(length=50), nullable=True),
        sa.Column("avoid_tolls", sa.Integer(), nullable=True),
        sa.Column("avoid_highways", sa.Integer(), nullable=True),
        sa.Column("avoid_ferries", sa.Integer(), nullable=True),
        sa.Column("avoid_unpaved", sa.Integer(), nullable=True),
        sa.Column("route_data", sa.JSON(), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_routes_created_at"), "routes", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_routes_id"), "routes", ["id"], unique=False)
    op.create_index(
        op.f("ix_routes_route_id"), "routes", ["route_id"], unique=True
    )
    op.create_index(
        op.f("ix_routes_user_id"), "routes", ["user_id"], unique=False
    )
    op.create_table(
        "saved_places",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("address", sa.Text(), nullable=True),
        sa.Column("category", sa.String(length=100), nullable=True),
        sa.Column("lat", sa.Float(), nullable=False),
        sa.Column("lng", sa.Float(), nullable=False),
        sa.Column("tags", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_saved_places_id"), "saved_places", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_saved_places_user_id"),
        "saved_places",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "route_waypoints",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("route_id", sa.Integer(), nullable=False),
        sa.Column("lat", sa.Float(), nullable=False),
        sa.Column("lng", sa.Float(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("address", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["route_id"], ["routes.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_route_waypoints_id"), "route_waypoints", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_route_waypoints_route_id"),
        "route_waypoints",
        ["route_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_route_waypoints_route_id"), table_name="route_waypoints"
    )
    op.drop_index(op.f("ix_route_waypoints_id"), table_name="route_waypoints")
    op.drop_table("route_waypoints")
    op.drop_index(op.f("ix_saved_places_user_id"), table_name="saved_places")
    op.drop_index(op.f("ix_saved_places_id"), table_name="saved_places")
    op.drop_table("saved_places")
    op.drop_index(op.f("ix_routes_user_id"), table_name="routes")
    op.drop_index(op.f("ix_routes_route_id"), table_name="routes")
    op.drop_index(op.f("ix_routes_id"), table_name="routes")
    op.drop_index(op.f("ix_routes_created_at"), table_name="routes")
    op.drop_table("routes")
    # ### end Alembic commands ###
