"""traffic

Revision ID: 5824bf51c343
Revises: 
Create Date: 2025-10-01 16:27:44.695300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5824bf51c343"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "incident_votes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("incident_id", sa.String(length=100), nullable=False),
        sa.Column("user_id", sa.String(length=100), nullable=True),
        sa.Column("vote_type", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_incident_votes_id"), "incident_votes", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_incident_votes_incident_id"),
        "incident_votes",
        ["incident_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_incident_votes_user_id"),
        "incident_votes",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "traffic_incidents",
        sa.Column("id", sa.String(length=100), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "accident",
                "construction",
                "closure",
                "congestion",
                "weather",
                "hazard",
                "other",
                name="incidenttype",
            ),
            nullable=False,
        ),
        sa.Column(
            "severity",
            sa.Enum(
                "low", "medium", "high", "critical", name="incidentseverity"
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "active",
                "resolved",
                "verified",
                "disputed",
                name="incidentstatus",
            ),
            nullable=True,
        ),
        sa.Column("latitude", sa.Float(), nullable=False),
        sa.Column("longitude", sa.Float(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("address", sa.String(length=500), nullable=True),
        sa.Column("affected_lanes", sa.String(length=200), nullable=True),
        sa.Column("estimated_duration", sa.String(length=100), nullable=True),
        sa.Column("reported_by", sa.String(length=100), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("votes_confirm", sa.Integer(), nullable=True),
        sa.Column("votes_dispute", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_traffic_incidents_created_at"),
        "traffic_incidents",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_traffic_incidents_id"),
        "traffic_incidents",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_traffic_incidents_latitude"),
        "traffic_incidents",
        ["latitude"],
        unique=False,
    )
    op.create_index(
        op.f("ix_traffic_incidents_longitude"),
        "traffic_incidents",
        ["longitude"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_traffic_incidents_longitude"), table_name="traffic_incidents"
    )
    op.drop_index(
        op.f("ix_traffic_incidents_latitude"), table_name="traffic_incidents"
    )
    op.drop_index(
        op.f("ix_traffic_incidents_id"), table_name="traffic_incidents"
    )
    op.drop_index(
        op.f("ix_traffic_incidents_created_at"), table_name="traffic_incidents"
    )
    op.drop_table("traffic_incidents")
    op.drop_index(
        op.f("ix_incident_votes_user_id"), table_name="incident_votes"
    )
    op.drop_index(
        op.f("ix_incident_votes_incident_id"), table_name="incident_votes"
    )
    op.drop_index(op.f("ix_incident_votes_id"), table_name="incident_votes")
    op.drop_table("incident_votes")
    # ### end Alembic commands ###
