services:
    web:
        image: josephgotran/routing-service:latest
        container_name: routing_service
        restart: always
        command: >
            sh -c "./docker-entrypoint.sh && uvicorn main:app --reload"
        environment:
            - DB_DEV_ROUTING_NAME=${DB_DEV_ROUTING_NAME:-gos_routing}
            - DB_DEV_USER=${DB_DEV_USER:-admin}
            - DB_DEV_PASSWORD=${DB_DEV_PASSWORD:-admin}
            - DB_DEV_HOST=host.docker.internal
            - DB_DEV_PORT=5432
        ports:
            - 8001:8001
        networks:
            - traffic_net


networks:
    traffic_net:
        external: true
