services:
    routing:
        image: josephgotran/routing-service:latest
        container_name: routing_service
        restart: always
        command: >
            sh -c "./docker-entrypoint.sh && uvicorn main:app --host 0.0.0.0 --port 8001"
        environment:
            - DB_DEV_ROUTING_NAME=${DB_DEV_ROUTING_NAME:-gos_routing}
            - DB_DEV_USER=${DB_DEV_USER:-admin}
            - DB_DEV_PASSWORD=${DB_DEV_PASSWORD:-admin}
            - DB_DEV_HOST=${DB_DEV_HOST:-db}
            - DB_DEV_PORT=${DB_DEV_PORT:-5432}
            - TOMTOM_API_KEY=${TOMTOM_API_KEY}
        labels:
            - "traefik.enable=true"
            - "traefik.http.services.routing.loadbalancer.server.port=8001"
            - "traefik.http.routers.routing.rule=Host(`api.joseph.works`) && PathPrefix(`/routing`)"
            - "traefik.http.routers.routing.entrypoints=websecure"
            - "traefik.http.routers.routing.tls.certresolver=letsencrypt"
            - "traefik.http.middlewares.routing-strip-prefix.stripprefix.prefixes=/routing"
            - "traefik.http.routers.routing.middlewares=jwt-verify@file,routing-strip-prefix@docker"
        networks:
            - traffic_net

networks:
    traffic_net:
        external: true
