[tool.black]
line-length = 79
target-version = ['py311']
exclude = '''
/(
    alembic
|   __pycache__
|   env
|   .env
)/
'''

[tool.isort]
profile = "black"
line_length = 79
skip = ["alembic", ".env", "env"]
